version: "3.3"
services:
    php:
        image: "php"
        volumes:
            - ./:/var/www/html
    web:
        image: nginx:1.17
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf

        ports:
            - "8000:80"

    db:
        container_name: mysql
        image: mysql:8
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./draft.sql:/docker-entrypoint-initdb.d/draft.sql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    # Node Service
    node:
        image: "node"
        volumes:
            - ./:/assets
