name: Run tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # - name: Execute tests (Unit and Feature tests) via PHPUnit

      #   run: ./vendor/bin/pest
      # - name: Run tests
      #   run: php artisan test
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Pull Docker Compose Configuration
      #   run: |
      #     curl -o docker-compose.yml https://github.com/shashidas95/basic_ci_cd/main/docker-compose.yml

      - name: Build  Docker Image php

        run:  docker build -t php -f Dockerfile.php .
      - name: Build  Docker Image node
        run:  docker build -t node -f Dockerfile.node .


      # - name: Deploy Docker Compose
      #   run: docker-compose up -d
